version: '1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ret_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    networks:
      - localhubs
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localhubs
    command: "iex -S mix phx.server"
    volumes:
      - .:/app/storage/dev
networks:
  localhubs:
