version: '1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ret_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    user: postgres
    networks:
      - localhubs
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hubs:
    image: stantop/local-hubs
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localhubs
    command: "npm run dev"
    volumes:
      - .:/app/storage/dev

  dialog:
    image: stantop/local-dialog
    ports:
      - "4443:4443"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localhubs
    command: "node index.js"
    volumes:
      - .:/dialog/storage/dev

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localhubs
    command: "mix phx.server"
    volumes:
      - .:/app/storage/dev
networks:
  localhubs:
